List = []
List.append([2,3])
print(List)
List.insert(1,100)
print(List)
List.insert(0, 'Geeks')
print(List)
List.extend([8, 'Geeks', 'Always'])
print(List)
List.remove(8)
print(List)
List.remove([2,3])
print(List)
List.pop()
print(List)
List.pop(1)
print(List)